[IaC] Terraform
dan-v/awslambdaproxy pull request #15
Opened 2020-04-27 15:28 UTC by yurymkomarov

Hello @dan-v !

I've created Terraform IaC configuration for awslambdaproxy application.

Please review my PR and let me know if u have any comments.

2020-04-28 06:55 UTC, dan-v requested changes
@yurymkomarov - thanks for the high quality PR. This is really well done! I have a few minor comments to address. I also don't want to include the function.zip in the git repo itself. I see that you updated make/circleci to add that artifact which is fine. Maybe the readme can just have a step (once i publish release with the lambda.zip) that says to pull down the latest lambda.zip into your directory.

2020-04-28 06:55 UTC, dan-v commented on iac/terraform/data.tf
> +  default = true
this will break for users without a default vpc (i have a few regions like that); probably not a huge deal though, but might be worth mentioning / commenting. i guess the safest way would be to build out a new vpc, but that might be overkill.

2020-04-28 06:55 UTC, dan-v commented on iac/terraform/main.tf
> +  proxy_credentials = var.proxy_credentials == null ? "${random_string.this.result}:${random_password.this.result}" : var.proxy_credentials
👍

2020-04-28 06:55 UTC, dan-v commented on iac/terraform/main.tf
> +  name               = "awslambdaproxy-role"
let's make this a unique name from the manual install (e.g. awslambdaproxy-role-iac, awslambdaproxy-role-terraform, etc), so there aren't conflicts.

2020-04-28 06:55 UTC, dan-v commented on iac/terraform/data.tf
> +data "aws_ip_ranges" "lambda" {
👍

2020-04-28 06:55 UTC, dan-v commented on iac/terraform/data.tf
> +    resources = ["arn:aws:iam::*:role/awslambdaproxy-role"]
reference role name instead of hardcoded

2020-04-28 06:55 UTC, dan-v commented on iac/terraform/data.tf
> +    resources = ["arn:aws:lambda:*:*:function:awslambdaproxy"]
reference function name instead of hardcoded (although it's hardcoded in current code)

2020-04-28 06:55 UTC, dan-v commented on iac/terraform/main.tf
> +    public_key  = tls_private_key.ec2.public_key_openssh
might be worth mentioning how to get your autogenerated ssh key so users could ssh into instance and debug if needed or just make it an output.

2020-04-28 06:55 UTC, dan-v commented on iac/terraform/main.tf
> +  function_name = "awslambdaproxy"
i'd like function name to be configurable, but right now it's hardcoded in code. if you could turn it into a variable anyways, so that way if i make the change in code i can just change the default variable for terraform.

2020-05-01 04:05 UTC, dan-v commented
One more request. I pushed a new release and changed up the structure of this package. If you could migrate your terraform to the `deployment` directory that would be ideal. I also included the lambda.zip file in latest release.

2020-05-01 14:49 UTC, yurymkomarov commented on iac/terraform/data.tf
> +  default = true
I will add logical condition with two states: use default VPC (if it available) or create private VPC with public subnet

2020-05-01 14:50 UTC, yurymkomarov commented on iac/terraform/main.tf
> +  proxy_credentials = var.proxy_credentials == null ? "${random_string.this.result}:${random_password.this.result}" : var.proxy_credentials
We should not forget about security, yes? )

2020-05-01 14:51 UTC, yurymkomarov commented on iac/terraform/main.tf
> +  name               = "awslambdaproxy-role"
What if we will add flags for custom IAM role and lambda function names?

2020-05-01 14:52 UTC, yurymkomarov commented on iac/terraform/data.tf
> +    resources = ["arn:aws:iam::*:role/awslambdaproxy-role"]
The same point: https://github.com/dan-v/awslambdaproxy/pull/15#discussion_r418576013

2020-05-01 14:52 UTC, yurymkomarov commented on iac/terraform/data.tf
> +    resources = ["arn:aws:lambda:*:*:function:awslambdaproxy"]
The same point: https://github.com/dan-v/awslambdaproxy/pull/15#discussion_r418576013

2020-05-01 14:53 UTC, yurymkomarov commented on iac/terraform/main.tf
> +    public_key  = tls_private_key.ec2.public_key_openssh
Oh, yeah. Will update README

2020-05-01 14:53 UTC, yurymkomarov commented on iac/terraform/main.tf
> +  function_name = "awslambdaproxy"
The same point: https://github.com/dan-v/awslambdaproxy/pull/15#discussion_r418576013

2020-05-01 14:56 UTC, yurymkomarov commented
> I also don't want to include the function.zip in the git repo itself
It was "hello world" lambda code. It's not possible to create lambda function without artifact )

2020-05-01 15:04 UTC, dan-v commented on iac/terraform/main.tf
> +  name               = "awslambdaproxy-role"
yes, that would be perfect

2020-05-02 12:37 UTC, yurymkomarov commented
Hello @dan-v ,

I've made a lot of updates. Please re-review my PR.

2020-05-02 21:57 UTC, dan-v reviewed
@yurymkomarov - this is looking great! thanks for tackling the cli changes as well for function and role name. just a few comments/questions for you.

2020-05-02 21:57 UTC, dan-v commented on deployment/terraform/main.tf
> +  source  = "yurymkomarov/vpc-single-public/aws"
any chance you could pull this module into the source tree? i'd prefer to not have external dependency for that.

2020-05-02 21:57 UTC, dan-v commented on deployment/terraform/lambda.tf
> +  count    = contains(var.lambda_regions, "ap-northeast-1") ? 1 : 0
should be 'us-east-1' here

2020-05-02 21:57 UTC, dan-v commented on deployment/terraform/lambda.tf
> +resource "aws_lambda_function" "ap-northeast-1" {
just want to make sure that i'm following your thought process here; you are pre-creating the lambda functions for the sake of being able to properly cleanup? just want to make sure, as the current code creates/updates already, but it would definitely make sense for cleanup purposes which the current code does not address.

2020-05-02 22:01 UTC, yurymkomarov commented on deployment/terraform/lambda.tf
> +resource "aws_lambda_function" "ap-northeast-1" {
yeah, you are fully right )

2020-05-02 22:01 UTC, yurymkomarov commented on deployment/terraform/lambda.tf
> +  count    = contains(var.lambda_regions, "ap-northeast-1") ? 1 : 0
shame on me...

2020-05-02 22:14 UTC, dan-v commented
I'd also not mind placing this first in the README as the preferred method of deployment. This really streamlines the process quite nicely. Also, if I add a section to contributors for this project - would you like me to add you and if so anything you'd want me to link to?

2020-05-02 22:17 UTC, yurymkomarov commented
> I'd also not mind placing this first in the README as the preferred method of deployment. This really streamlines the process quite nicely. Also, if I add a section to contributors for this project - would you like me to add you and if so anything you'd want me to link to?

Okay, I will update README too.
And yeah, you can add me as contributor. As link I will preferred github page (because I can't finish my personal website for... 4 months 🤣 )

2020-05-02 22:18 UTC, yurymkomarov commented on deployment/terraform/main.tf
> +  source  = "yurymkomarov/vpc-single-public/aws"
The task is in progress... Give me 15 minutes, please )

2020-05-02 23:33 UTC, dan-v approved these changes
Awesome. Thanks for clarification and making those changes! I'm going to merge this in, and I'll work on updating the README with contributor section soon. Thanks a ton for this contribution.

2020-05-02 23:35 UTC, yurymkomarov commented
You are always welcome ) Let me know if u will need help in TF updates/bug fixes )

2020-05-02 23:35 UTC, merged