Automatically provision AWS resources with Terraform
dan-v/awslambdaproxy pull request #9
Opened 2019-10-20 18:06 UTC by 3m3x

# Background
Provisioning the infrastructure to run awslambdaproxy is manual, tedious and laborious. This friction presents a barrier to first-time usage.

# Changes
This PR introduces a Terraform script which provisions:
* a VPC and internet gateway
* a subnet and route table
* an EC2 instance for the `awslambdaproxy` program
* a Security Group which permits access to the EC2 instance, and permits traffic between the EC2 instance and the Lambdas
* an IAM EC2 role with the `iam/setup.json` policy attached

A simple wrapper script `deploy.sh` kicks off the deployment and then presents the user with a ssh command to run that will start the proxy. If I weren't so lazy I would've put the proxy under control of the supervisor daemon but I think this is good enough for now.

The "Installation" section of `README.md` has also been updated to include usage of this script.

2019-10-20 21:54 UTC, dan-v requested changes
thanks for the PR @3m3x! i definitely like the overall idea of simplifying the setup with terraform. there's a few things i'd like to see tweaked before accepting:
* rather than setting defaults in the tf file (like regions, ssh key, etc), if you could pull that out into a config file it would be easier to see what options are being set / can be customized. the readme could just have an additional bit about tweaking the config file to your liking or whatever.
* for security reasons, i'd definitely prefer the primary port 8080 was not open to the world by default. if this could be locked down to users current IP by default that would be better (could still have option to open to world if that's what someone wants).
* for security reasons, if you could generate a random password or have it be a config value that would be better as well. this is especially important if it is being opened to the world as it would have default well known values right now.
* if you could update the existing deploy script to have option to tear down the terraform infrastructure or create a separate script to do that it would help make this a bit more streamlined. the current approach with remote-exec is kind of a one shot deal on deployment, so if you want to tweak or make changes it would be easy enough to tear it down, edit config file, and deploy a new one.
* agreed that it would be nice to have it run in supervisor like systemd, but fine with the way it is.

2019-10-20 21:54 UTC, dan-v commented on README.md
> +j Powered by
?

2019-10-20 21:54 UTC, dan-v commented on aws.tf
> +  ami           = "ami-0532935b53d8e05ee"
make this a variable

2019-10-20 21:54 UTC, dan-v commented on aws.tf
> +  instance_type = "t2.micro"
make this a variable

2019-10-20 21:54 UTC, dan-v commented on aws.tf
> +    user  = "ubuntu"
make this a variable

2019-10-20 21:54 UTC, dan-v commented on deploy.sh
> +IP=54.123.23.300
all of the terraform code here is commented out and this is hardcoded, guessing you just forgot to swap it back from testing

2019-10-20 21:54 UTC, dan-v commented on aws.tf
> +variable "package-url" {
make version of package a variable

2019-10-22 03:29 UTC, 3m3x commented on README.md
> +j Powered by
sorry, typo

2019-10-22 04:35 UTC, 3m3x commented
These changes address the points you raised earlier.

The proxy is only accessible via a SSH tunnel that is locally bound to 127.0.0.1:8080 which also makes configuring the browser's proxy settings much simpler.

TODO:
* update README

2019-10-22 05:06 UTC, dan-v reviewed
This is looking much better! Thanks for taking the time to fix these items. Once you update the README LGTM.

2020-05-03 04:00 UTC, dan-v commented
Closing this out in favor of #15 as it's more comprehensive. Thanks for the initial PR though @3m3x!

2020-05-03 04:00 UTC, closed without merging